# Supabase PostgreSQL Configuration

database_url = "postgresql://postgres.qnnwnqsitsyegqeceypk:5uGkDiIthYfb3kx1@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"

# Admin password for application
ADMIN_PASSWORD = "1997"

# Supabase project details (optional, for reference)
[supabase]
database_url = "postgresql://postgres.qnnwnqsitsyegqeceypk:5uGkDiIthYfb3kx1@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
host = "aws-1-ap-southeast-1.pooler.supabase.com"
port = "6543"
database = "postgres"
user = "postgres.qnnwnqsitsyegqeceypk"
pool_mode= "transaction"